In [2]:
import numpy as np
np.__version__

'1.24.3'

In [4]:
# Create a Numpy array

arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
# Numpy vs List
list1 = [1,2,3,4,5]
print(list1*2)

arr = np.array([10,20,30,40])
print(arr*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[20 40 60 80]


In [10]:
list1 = [10, 2.56, 'python', True]
print(list1)

arr = np.array([10, 2.56, 'Python', True]) #dont use different datatypes in array
print(arr)

[10, 2.56, 'python', True]
['10' '2.56' 'Python' 'True']


In [11]:
# Array: Create 1D and 2D array

arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [ ]:
# Shapes Property is used to determine the dimension of array
#For 1D array: Shape returns n
# n = Number of element in the array

# For 2D array: Shape returns n,m
# n = Number of Rows and m = Number of Column

#For 3D array: Shape returns x,y,z

In [14]:
# 2D array

twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)
print(twoD.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
