In [2]:
import numpy as np
np.__version__

'1.24.3'

In [3]:
# Create a Numpy array

arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
# Numpy vs List
list1 = [1,2,3,4,5]
print(list1*2)

arr = np.array([10,20,30,40])
print(arr*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[20 40 60 80]


In [5]:
list1 = [10, 2.56, 'python', True]
print(list1)

arr = np.array([10, 2.56, 'Python', True]) #dont use different datatypes in array
print(arr)

[10, 2.56, 'python', True]
['10' '2.56' 'Python' 'True']


In [6]:
# Array: Create 1D and 2D array

arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [7]:
# Shapes Property is used to determine the dimension of array
#For 1D array: Shape returns n
# n = Number of element in the array

# For 2D array: Shape returns n,m
# n = Number of Rows and m = Number of Column

#For 3D array: Shape returns x,y,z

In [8]:
# 2D array

twoD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)
print(twoD.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [9]:
# Create 4x3 Matrix using array

arr = np.array([[1,2,3],[4,5,6],[7,8,9,],[10,11,12]])
print(arr)
print(arr.shape)

# 2x3 Matrix

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
# Indexing and Slicing

arr = np.array([1,2,3])
print(arr.shape)

print(arr[0])
print(arr[-2])
print(arr[::-1])
print(arr[0:2])

(3,)
1
2
[3 2 1]
[1 2]


In [13]:
arr =  np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given